### ISSUE TITLE
One or more build-args [site_root] were not consumed, failing build

### ISSUE THREAD

**Issue by SupraRon** [Microsoft/aspnet-docker#11]
Using the sample Dockerfile, I am getting the following error during build:

PS C:\containers\ASP5> docker build -t aspnet-site --build-arg site_root=/ .
Sending build context to Docker daemon 7.946 MB
Step 1/2 : FROM microsoft/iis
 ---> 211fecef1e6b
Step 2/2 : RUN powershell -Command Add-WindowsFeature NET-Framework-45-ASPNET;     powershell -Command Add-WindowsFeature Web-Asp-Net45;     powershell -Command Remove-Item -Recurse C:\inetpub\wwwroot\*
 ---> Running in 9d45db46a8a9

Success

 Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {ASP.NET 4.6}

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Application Development, ASP.NET 4.6,...

 ---> 1530caa06fad
Removing intermediate container 9d45db46a8a9
**One or more build-args [site_root] were not consumed, failing build.**

Any idea what is causing this? Appreciate any feedback.

Thanks,

Ron

**Comment by mayankthebest** [comment]
This because the wrong dockerfile is linked in the documentation. The correct dockerfile is here - https://github.com/Microsoft/aspnet-docker/blob/master/4.6.2/sample/Dockerfile

Contents of Dockerfile:
```
FROM microsoft/aspnet
ARG site_root=.
ADD ${site_root} /inetpub/wwwroot
```
You can see that now we make use of the build args to add the site root to IIS root.
