### ISSUE TITLE
encountered an error during Start: failure in a Windows system call: The JSON document is invalid. (0xc037010d)

### ISSUE THREAD

**Issue by odin88** [microsoft/aspnet-docker#111]
PS C:\Users\hassan> e:
PS E:\> cd E:\DockerizeHassan\aspnet
PS E:\DockerizeHassan\aspnet>  docker build -t aspnet-site --build-arg site_root=/ .
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803
4.7.2-runtime-windowsservercore-1803: Pulling from microsoft/dotnet-framework
d9e8b01179bf: Downloading
65a09b62c235: Downloading
a4b72aa6cfe8: Download complete
image operating system "windows" cannot be used on this platform
PS E:\DockerizeHassan\aspnet>  docker build -t aspnet-site --build-arg site_root=/ .
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803
4.7.2-runtime-windowsservercore-1803: Pulling from microsoft/dotnet-framework
d9e8b01179bf: Pull complete
65a09b62c235: Extracting [==================================================>]  254.5MB/254.5MB
a4b72aa6cfe8: Download complete
PS E:\DockerizeHassan\aspnet>  docker build -t aspnet-site --build-arg site_root=/ .
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803
4.7.2-runtime-windowsservercore-1803: Pulling from microsoft/dotnet-framework
d9e8b01179bf: Already exists
65a09b62c235: Pull complete
a4b72aa6cfe8: Pull complete
Digest: sha256:c2586af354bc76c2f431e3d6584bd38c277b896a6a5b07dc0042b4ff7480956f
Status: Downloaded newer image for microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803
 ---> 98db70b6a5dc
Step 2/7 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in e0bc7505a569
Removing intermediate container e0bc7505a569
 ---> a5a84e2da180
Step 3/7 : RUN Add-WindowsFeature Web-Server;     Add-WindowsFeature NET-Framework-45-ASPNET;     Add-WindowsFeature Web-Asp-Net45;     Remove-Item -Recurse C:\inetpub\wwwroot\*;     Invoke-WebRequest -Uri https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.3/ServiceMonitor.exe -OutFile C:\ServiceMonitor.exe
 ---> Running in c91c062ccb74
container c91c062ccb74dafbc2b0b6dee0aed7b578095bfe1c3346324319d031615e03d5 encountered an error during Start: failure in a Windows system call: The JSON document is invalid. (0xc037010d)
PS E:\DockerizeHassan\aspnet>  docker build -t aspnet-site --build-arg site_root=/ .
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803
 ---> 98db70b6a5dc
Step 2/7 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> a5a84e2da180
Step 3/7 : RUN Add-WindowsFeature Web-Server;     Add-WindowsFeature NET-Framework-45-ASPNET;     Add-WindowsFeature Web-Asp-Net45;     Remove-Item -Recurse C:\inetpub\wwwroot\*;     Invoke-WebRequest -Uri https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.3/ServiceMonitor.exe -OutFile C:\ServiceMonitor.exe
 ---> Running in fdbd12dcd8f3
container fdbd12dcd8f3356535a79362a213b98e421670ded4dfde06e738d1622d565b38 encountered an error during Start: failure in a Windows system call: The JSON document is invalid. (0xc037010d)
PS E:\DockerizeHassan\aspnet> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS E:\DockerizeHassan\aspnet>  docker build -t aspnet-site --build-arg site_root=/ .
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803
 ---> 98db70b6a5dc
Step 2/7 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> a5a84e2da180
Step 3/7 : RUN Add-WindowsFeature Web-Server;     Add-WindowsFeature NET-Framework-45-ASPNET;     Add-WindowsFeature Web-Asp-Net45;     Remove-Item -Recurse C:\inetpub\wwwroot\*;     Invoke-WebRequest -Uri https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.3/ServiceMonitor.exe -OutFile C:\ServiceMonitor.exe
 ---> Running in b1408d60b34e
container b1408d60b34e8ff305fb4b89444c996de0247ea8f19486acb325b52860ff6650 encountered an error during Start: failure in a Windows system call: The JSON document is invalid. (0xc037010d)
PS E:\DockerizeHassan\aspnet>

**Comment by HongGit** [comment]
@odin88 you will need to Windows version 1803 to pull down microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803 image.
