### ISSUE TITLE
My web service fails with error "Failed to start monitoring changes to App_Offline.htm"

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/aspnet-docker#115]
_From @pbalzer on May 18, 2018 13:9_

I tried to change the user account of the application pool, I tried giving Full Access to Everyone in the containing folder, but nothing, I get always the same error. 
This happens only on the 1709 version, in the 1603 version it works.

_Copied from original issue: Microsoft/iis-docker#103_

**Comment by Jinhuafei** [comment]
@pbalzer Would you please share the docker file? Does this issue only happen to app_offline.htm file?

**Comment by Jinhuafei** [comment]
Since we don't have enough info about the issue, close for now. Feel free to reopen the issue later with some details.
