### ISSUE TITLE
These images are hard to use

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/aspnet-docker#119]
Whoever added this:

"Note: Multi-arch tags, such as 4.7.1, have been updated to use windowsservercore-1709 images if your host is Windows Server 1709 or higher or Windows 10 Fall Creators Update (Version 1709) or higher. You need Docker 17.10 or later to take advantage of these updated tags."

Does not understand the whole point of containers.  Regardless of where you build your container, you should get the same result!  This is utterly broken.

**Comment by MichaelSimons** [comment]
If you want to be tied to a specific platform, then you should be using a platform tag such as 4.7.1-windowsservercore-lstc2016.  The intent of multi-arch tags is that when you build on a specific platform, then you will get an image that will work with said platform.  The use of multi-arch tags is a practice that you see across the official Docker repos.  This allows users to pull image `X` from any platform and just have it work.
