### ISSUE TITLE
Missing or bad fragments

### ISSUE THREAD

**Issue by decarufe** [Microsoft/aspnet-docker#12]
I try to get microsoft/aspnet container but it fails on two fragments (9c7f9c7d9bc2 and d33fff6043a1). They retry for a while and fail with "unknown blob" message.

```
Using default tag: latest
latest: Pulling from microsoft/aspnet
9c7f9c7d9bc2: Retrying in 8 seconds
d33fff6043a1: Retrying in 9 seconds
b7c3bbe47489: Downloading [========>                                          ] 21.09 MB/123.8 MB
1028e286eae2: Waiting
28e6f26ee039: Waiting
a0db4e322336: Waiting
```

**Comment by shirhatti** [comment]
@shhsu Can you take a look?

**Comment by shhsu** [comment]
Can you try running & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon
Make sure you are using windows daemon

**Comment by decarufe** [comment]
That's it! You nailed it. I switched my docker server to Linux for another project and I forgot to set it back. It worked fine after I switch back to Windows. 

I know this is not related to this project but I think docker should give a little more info if it tries to pull a container from an unsupported OS.
