### ISSUE TITLE
Bump up ServiceMonitor issue for October releases

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/aspnet-docker#121]
Related https://github.com/Microsoft/iis-docker/issues/122

**Comment by liberdis** [comment]
What is this issue trying to say? I'm trying to find an answer to this error surfacing  during about 20% of my startups (I'm using aspnet:4.7.2-windowsservercore-ltsc2016) :

ERROR: Failed to stop or query status of service 'w3svc' error [800705b4]

This seems to have started in the last month or two, and I'm wondering if there was an update that caused it.

Is this issue related to my problem?

**Comment by shirhatti** [comment]
This issue was tracking https://github.com/Microsoft/aspnet-docker/pull/126 and should have been closed
