### ISSUE TITLE
Image size varies greatly on different OS version

### ISSUE THREAD

**Issue by rymancl** [Microsoft/aspnet-docker#123]
First, I apologize if this is a "user error" thing, but I can't see where I'm going wrong. 

**LOCAL - Windows 10 - 5.37GB**
`docker pull microsoft/aspnet:4.7.2`
`docker images`

```
REPOSITORY                                                                          TAG                                IMAGE ID            CREATED             SIZE
microsoft/aspnet                                                                    4.7.2                              21a4756c6eac        2 weeks ago         5.37GB
```
If I inspect this image, here are some properties of relevance...

```
"microsoft/aspnet@sha256:5afdec531eaa50f43c0f513355894fbe93398cec877910cc083ae1eb19a38f37"
...
"Created": "2018-09-12T02:05:35.3971731Z",
...
"Os": "windows",
"OsVersion": "10.0.17134.285",
```

`docker history microsoft/aspnet:4.7.2`
```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
21a4756c6eac        2 weeks ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference =…   238MB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference =…   247MB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 weeks ago         cmd /S /C #(nop)  ENV COMPLUS_NGenProtectedP…   41kB
<missing>           2 weeks ago         Install update 10.0.17134.285                   1.2GB
<missing>           5 months ago        Apply image 10.0.17134.1                        3.68GB
```

---------------------------------------

**BUILD SERVER - Windows Server 2016 - 13.6GB**
`docker pull microsoft/aspnet:4.7.2`
`docker images`

```
REPOSITORY                                                                          TAG                                IMAGE ID            CREATED             SIZE
microsoft/aspnet                                                                    4.7.2                                       02dfa1e1baeb        2 weeks ago         13.6GB
```
If I inspect this image, here are some properties of relevance...

```
"microsoft/aspnet@sha256:5afdec531eaa50f43c0f513355894fbe93398cec877910cc083ae1eb19a38f37"
...
"Created": "2018-09-12T02:26:46.5749899Z",
...
"Os": "windows",
"OsVersion": "10.0.14393.2485",
```

`docker history microsoft/aspnet:4.7.2`
```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
02dfa1e1baeb        2 weeks ago         powershell -Command $ErrorActionPreference...   41kB                
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB                
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB                
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   193MB               
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   348MB               
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB                
<missing>           2 weeks ago         cmd /S /C \Windows\Microsoft.NET\Framework...   999MB               
<missing>           2 weeks ago         cmd /S /C #(nop)  ENV COMPLUS_NGenProtecte...   41kB                
<missing>           2 weeks ago         cmd /S /C powershell -Command         $Err...   329MB               
<missing>           2 weeks ago         cmd /S /C powershell Invoke-WebRequest -Ur...   879MB               
<missing>           2 weeks ago         Install update 10.0.14393.2485                  3.21GB              
<missing>           21 months ago       Apply image 10.0.14393.0                        7.68GB
```

---------------------------------------

So my question is, what is causing this massive variation in image size? It's using the same sha for both images. I see the same results using latest instead of 4.7.2 as well. I've tried pruning my images and re-pulling and I get the same results. 

I see the history is different, which looks like is what is making it so big. I'm just confused as to why. Is it because of the Windows versions?

Any insight would be awesome. Thanks!

**Comment by MichaelSimons** [comment]
This is because the 4.7.2 tag is a [multi-arch tag](https://blog.docker.com/2017/11/multi-arch-all-the-things/).  A multi-arch tag is a special tag that points to different concrete images that are platform specific.  If you pull a multi-arch tag from different platforms, you will get different images.  On windows you have to keep in mind that there are [compatibility limitations](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) with the Windows base images.  The windows base images have gone a big diet since they were originally released (e.g. microsoft/windowsservercore:ltsc2016 - 10.7 GB vs microsoft/windowsservercore:1803 - 4.88 GB)

If you want/need to be explicit in which OS you are based on, then use the OS qualified tags - microsoft/aspnet:4.7.2-windowsservercore-ltsc2016 or microsoft/aspnet:4.7.2-windowsservercore-1803

**Comment by rymancl** [comment]
> This is because the 4.7.2 tag is a [multi-arch tag](https://blog.docker.com/2017/11/multi-arch-all-the-things/). A multi-arch tag is a special tag that points to different concrete images that are platform specific. If you pull a multi-arch tag from different platforms, you will get different images. On windows you have to keep in mind that there are [compatibility limitations](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) with the Windows base images. The windows base images have gone a big diet since they were originally released (e.g. microsoft/windowsservercore:ltsc2016 - 10.7 GB vs microsoft/windowsservercore:1803 - 4.88 GB)
> 
> If you want/need to be explicit in which OS you are based on, then use the OS qualified tags - microsoft/aspnet:4.7.2-windowsservercore-ltsc2016 or microsoft/aspnet:4.7.2-windowsservercore-1803

Thanks for the reply. That makes sense. I was reading about multi-arch but I guess it just didn't click. I'm assuming then that "latest" is inherently multi-arch as well since I see the same thing with that?

I did also try using microsoft/aspnet:4.7.2-windowsservercore-ltsc2016 but it ended up being 13.6GB on my local PC and on the server, so I was just trying to find one a bit smaller. It was confusing me since it says on DockerHub it is 7GB but what I was getting was so much larger. I was excited to find an aspnet image around 5GB, but I guess I won't be able to for Windows Server 2016.

**Comment by MichaelSimons** [comment]
> I'm assuming then that "latest" is inherently multi-arch as well since I see the same thing with that?

Yes you are correct

> It was confusing me since it says on DockerHub it is 7GB but what I was getting was so much larger.

The number reported on the tags tab of DockerHub is the compressed size (e.g. the size of the bits sent over the wire when you pull).  You would need to upgrade to Windows Server 2016, version 1709 or version 1803 to make use of the smaller images.  Windows Server 2019 is your next option...

**Comment by rymancl** [comment]
> You would need to upgrade to Windows Server 2016, version 1709 or version 1803 to make use of the smaller images. Windows Server 2019 is your next option...

Just to clarify, this is because of direct compatibility between the host OS and the image right? When versions don't match, it needs to pull in the extra layers for compatibility right?

**Comment by MichaelSimons** [comment]
> Just to clarify, this is because of direct compatibility between the host OS and the image right?

Correct - I would word it as there is compatibility limitations between the host OS and container OS.

> When versions don't match, it needs to pull in the extra layers for compatibility right?

No - When they don't match, you may not be able to run the image on your host at all or if supported, you must run with `hyperv` isolation.  See https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility for details.

The image size of a particular OS image is always the same no matter where it is run.
