### ISSUE TITLE
Change properties Application Pool

### ISSUE THREAD

**Issue by alexandresmoraes** [microsoft/aspnet-docker#124]
how to change iis properties, same as picture:

![sem titulo](https://user-images.githubusercontent.com/26805150/46349122-8f991a80-c627-11e8-863b-a54c781f33a3.png)

**Comment by pbering** [comment]
I normally use: 
```Dockerfile
RUN Import-Module WebAdministration; Set-ItemProperty -Path 'IIS:\AppPools\DefaultAppPool' -Name 'enable32BitAppOnWin64' -Value 'True'; 
```
