### ISSUE TITLE
Add support for Windows Server 2019

### ISSUE THREAD

**Issue by sixeyed** [Microsoft/aspnet-docker#125]
The Windows Server Core Docker image is GA now  at `mcr.microsoft.com/windows/servercore:1809` - it would be great to get ASP.NET images for 1809 (we already have them for ASP.NET Core via [PR 719](https://github.com/dotnet/dotnet-docker/pull/719)).

**Comment by sanguedemonstro** [comment]
I'm with you @sixeyed , actually I'm waiting, and ready to test my apps on it.
Please put it at Docker Hub too!

**Comment by shirhatti** [comment]
We have the PR staged at https://github.com/Microsoft/aspnet-docker/tree/RS5update and are working on bootstrapping new infrastructure to publish to Windows Server 2019

**Comment by radyz** [comment]
Excellent, looking forward to download it once it's ready

**Comment by radyz** [comment]
Any ETA on this?

Thanks

**Comment by radyz** [comment]
Thanks a lot!! I've been refreshing docker hub everyday checking for it to be available :smile:

**Comment by sanguedemonstro** [comment]
Any ETA on this?

Thanks

**Comment by pbering** [comment]
it's here: `docker image pull mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019`

**Comment by Mozanrath** [comment]
Still not on docker hub yet

**Comment by shirhatti** [comment]
@Mozanrath The images are already live.

As you may have noticed in the docker pull command, the image is now being served from the Microsoft Container Registry (MCR). Starting with Windows Server 2019 and going forwards, all new tags will be published exclusively to MCR. All existing tags have been syndicated from DockerHub to MCR.

If your existing Dockerfile begins by specifying microsoft/iis as the base layer as shown below-

```Dockerfile
FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
…
```

Our guidance is to move to adopting MCR as your base layer. You should change your Dockerfile to what’s shown below-

```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2016
…
```

As part of this transition, we are only changing the source from where you download your images to MCR. DockerHub continues to be the preferred medium for container image discovery.
Take a look [this blog post](https://azure.microsoft.com/en-us/blog/microsoft-syndicates-container-catalog/) for the motivation behind this change.

**Comment by Mozanrath** [comment]
Where can we see a list of images on mcr? Is there a web UI like docker hub?

**Comment by shirhatti** [comment]
@rotata Could you help answer with that question?

**Comment by sanguedemonstro** [comment]
> Starting with Windows Server 2019 and going forwards, all new tags will be published exclusively to MCR. All existing tags have been syndicated from DockerHub to MCR.

Hey @shirhatti, or @rotata, how can I list or explore all images and tags from mcr.microsoft.com?

**Comment by biiiipy** [comment]
@sanguedemonstro as I've read elsewhere, Docker Hub is still the place to explore/search images and mcr is just a place where they get pulled from. It's kind of weird and unexpected, but makes sense in a way

**Comment by sanguedemonstro** [comment]
@biiiipy from ltsc2019 on, tags are no longer in the docker hub. So now it is hard to know if there is any variant of ltsc2019, like other languages as pt-BR... Maybe there is but who knows?!
