### ISSUE TITLE
port binding not working

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/aspnet-docker#13]
_From @paddyfay on December 9, 2016 9:44_

I am trying to bind ports between my docker host and aspnet container. The container is created from the latest aspnet image. The following run command successfully starts the container however the aspnet site is only reachable from the private IP address of the container. 

docker run -d -p 80:80 --name=test-site asp-site

The relating entry in docker hub states that reaching the container using localhost from the host is not supported in the current release. Does this mean that using the private IP address of the host is also not supported?

_Copied from original issue: aspnet/aspnet-docker#179_

**Comment by shirhatti** [comment]
[There is a currently a known limitation in Windows NAT](https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/)

Here's the relevant section if you don't  want to read that entire article

> Internal endpoints assigned to VMs or containers cannot be accessed using the external IPs / ports referenced in NAT static port mappings directly from the NAT host. From the NAT host, these internal endpoints must be addressed directly by their internal IP and ports. For instance, assume a container endpoint has IP 172.16.1.100 and is running a web server which is listening on port 80. Moreover, assume a port mapping has been created through docker to forward traffic from the host’s IP address (10.10.50.20) received on TCP port 8080 to the container endpoint. In this case, a user on the container host cannot directly access the web server using the externally mapped ports. e.g. A user operating on the container host cannot access the container web server indirectly on http://10.10.50.20:8080. Instead, the user must directly access the container web server on http://172.16.1.100:80.

> The one caveat to this limitation is that the internal endpoint can be accessed using the external IP/port from a separate, VM/container endpoint running on the same NAT host: this is called hair-pinning. E.g. A user operating on container A can access a web server running in Container B using the internal IP and port of http://10.10.50.20:8080.

**Comment by paddyfay** [comment]
Any idea when this limitation will be overcome?

**Comment by JMesser81** [comment]
Soon... :-)

**Comment by mhedgpeth** [comment]
Thanks for the update @JMesser81. As I've gotten into windows virtualization, this is the one problem that keeps me from telling me that windows containers are ready to go. I'm looking forward to a fix.

**Comment by odalet** [comment]
Can't wait for this limitation to be fixed as well. Any uservoice of some kind for upvoting it?

**Comment by artisticcheese** [comment]
This is already causing confusion and anger (https://stackoverflow.com/questions/44817861/windows-container-port-binding-not-working-on-windows-server-2016-using-docker/44827162#44827162)

**Comment by mhedgpeth** [comment]
@shirhatti should this be reopened? Are there plans to fix this?

**Comment by 1oglop1** [comment]
Why is this not written in official documentation? I'm reading through it for 2 weeks and still finding only github issues with scattered information!
