### ISSUE TITLE
manifest for microsoft/aspnet:4.7.2-windowsservercore-ltsc2019 not found

### ISSUE THREAD

**Issue by alburgin** [Microsoft/aspnet-docker#146]
Hi,

I recently pulled the aspnet:4.7.2 windowsservercore docker image, and then tried building with it.  I used an existing dockerfile which worked with a previous version of the apsnet 4.7.2 docker image, but it is failing with the newer image.
The failure is that the manifest is not found (per the title).

Output:
docker build -t proxyfrontend.webrole:dev  "<project path>"
Sending build context to Docker daemon  248.4MB
Step 1/4 : FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2019
manifest for microsoft/aspnet:4.7.2-windowsservercore-ltsc2019 not found

**Comment by HongGit** [comment]
@alburgin the images are already live.

See #125 .

**Comment by HongGit** [comment]
In addition, the Readme is being updated with the announcement. 

See #132.
