### ISSUE TITLE
microsoft/aspnet:4.7.2-windowsservercore-1803 is not supported in web app windows container

### ISSUE THREAD

**Issue by JebasinghLuccas** [Microsoft/aspnet-docker#149]
I created a docker image based on microsoft/aspnet:4.7.2-windowsservercore-1803 and when i try to mount this from web app container , i ended up getting the below error 

Cannot run this Operating System/Version in Windows Containers. Maximum supported OS version is 10.0.14393.9999.

what is correct base image i could use ?

**Comment by shirhatti** [comment]
Have a look at https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#matching-container-host-version-with-container-image-versions

Given that you're running on a Windows Server 2016 host, the image you should be using is `mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2016`
