### ISSUE TITLE
Rebuild 3.5 tag on new windowsservercore base image version

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/aspnet-docker#15]
_From @git-jiby-me on December 25, 2016 19:8_

It seems the version of base image windowsservercore was updated (latest one is 10.0.14393.576), however it seems the 3.5 tag is not rebuild using the new base image, can you guys do that, so that we end up reusing the base image used by other images, and end up using the latest base image ?

_Copied from original issue: aspnet/aspnet-docker#181_

**Comment by shirhatti** [comment]
Fixed by #20
New ASP.NET 3.5 images are now available on DockerHub
