### ISSUE TITLE
[Powershell]  A positional parameter cannot be found that accepts argument

### ISSUE THREAD

**Issue by ebellumat** [microsoft/aspnet-docker#152]
I have this dockerfile.

In Windows 10 this line works perfectly, but on this image, i have this error.

`RUN powershell Start-Process -FilePath "C:\database\setup.exe" -argumentlist "-responsefile c:\database\client.rsp", "-silent" -wait`

What is the version of Powershell of this image? How can I fix this script to run on it?

Im triying to install Oracle Universal Installer because i Need the Oracle Client to run my Application on it.

![image](https://user-images.githubusercontent.com/26942680/50221090-3a91b880-037b-11e9-9003-ca7fece1b4ae.png)

`
FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2016

ARG source
WORKDIR /inetpub/wwwroot
#COPY ${source:-obj/Docker/publish} .
WORKDIR /
COPY database .
SHELL ["powershell", "-command"]
RUN powershell $PSVersionTable.PSVersion
RUN powershell Start-Process -FilePath "C:\database\setup.exe" -argumentlist "-responsefile c:\database\client.rsp", "-silent" -wait
ENTRYPOINT powershell`

**Comment by raget** [comment]
I had a similar problem. Try `RUN powershell Start-Process -FilePath 'C:\database\setup.exe' -argumentlist '-responsefile c:\database\client.rsp -silent' -wait`. RUN actually starts `cmd /S` so there could be a problem with qoutations and aposthrophs.
