### ISSUE TITLE
'Host.docker.internal' does not resolve from inside container

### ISSUE THREAD

**Issue by willemodendaal** [Microsoft/aspnet-docker#153]
I'm trying to call a service on the container host machine (for local dev environment only, not production). Other images, like `microsoft/nanoserver` allow me to ping host.docker.internal, but the `microsoft/aspnet:4.7.2-windowsservercore-1803` image just returns the following error:

```
PS C:\inetpub\wwwroot> ping host.docker.internal
Ping request could not find host host.docker.internal. Please check the name

```
Here is my dockerfile:
```

FROM microsoft/aspnet:4.7.2-windowsservercore-1803
EXPOSE 80
ARG source
WORKDIR /inetpub/wwwroot
COPY . .
ENTRYPOINT ["powershell"]
```

How do I call the host machine from my docker container? I'm using the default 'nat' network. Running on a Windows 10 laptop.

**Comment by StephenMolloy** [comment]
This would be an issue below our layer, and it looks like there already is an open issue for it.  https://github.com/docker/for-win/issues/1976
