### ISSUE TITLE
aspnet:4.7.2-windowsservercore-ltsc2019 printers not available

### ISSUE THREAD

**Issue by themultiplexer** [microsoft/aspnet-docker#156]
According to [this Issue](https://github.com/moby/moby/issues/37124) printers should work starting with 1809 or ltsc2019 but printers are still not available. I need this for GDI to work.

**Comment by shirhatti** [comment]
To the best of my understanding, you will need to use new [windows](https://hub.docker.com/_/microsoft-windowsfamily-windows) base image for printer support.
@cwilhit if he has more to add. 

Currently, our ASP.NET images are based on Windows Server Core images as opposed to the Windows images and we currently have no plans to create ASP.NET images based on the Windows base image. I'd recommend building your own images

**Comment by cwilhit** [comment]
Only thing I'd call out is setting expectations around "printers working in containers"--Yes, you can run the Print Spooler service in the _Windows_ base image as @shirhatti pointed out, provided you have it turned off on your host and there's only one instance of the service running. I suspect there will be other quirks as well. Would love to capture this feedback if you try it out @themultiplexer
