### ISSUE TITLE
microsoft/dotnet:2.2-runtime doesn't support Microsoft.AspNetCore.App@2.2.0

### ISSUE THREAD

**Issue by bdparrish** [Microsoft/aspnet-docker#158]
Utilizing the pattern of using `microsoft/dotnet:2.2-sdk` to build a ASP.NET Core 2.2 Angular templated app and then copying it to `microsoft/dotnet:2.2-runtime` for running the app.  However I get an error when running the image - `"Microsoft.AspNetCore.App" version "2.2.0" could not be found.`

Is it part of the workflow to restore different libraries in the runtime environment vs. the sdk?

```
FROM microsoft/dotnet:2.2-sdk as builder  
ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

<...brevity...>

WORKDIR /root/src/app/test
RUN dotnet restore ./test.csproj
RUN dotnet publish -c release -o published

FROM microsoft/dotnet:2.2-runtime
WORKDIR /root/
EXPOSE 80
COPY --from=builder /root/src/app/cogent-ui/published .
ENTRYPOINT ["dotnet", "cogent-ui.dll"]
```

**Comment by MichaelSimons** [comment]
@bdparrish - For running ASP.NET Core application, you should be using the [`aspnet-runtime` tag variants](https://github.com/dotnet/dotnet-docker#microsoftdotnetversion-aspnetcore-runtime).  The `runtime` tag variants only include the .NET Core runtime and do not include any ASP.NET Core components.
