### ISSUE TITLE
No matching manifest for unknown in the manifest list entries

### ISSUE THREAD

**Issue by tiwarishrijan** [Microsoft/aspnet-docker#163]
I am unable to pull microsoft images from docker .
for Ex; 
![image](https://user-images.githubusercontent.com/6523607/52636960-f68ee000-2ef3-11e9-8996-444306c68a5f.png)

**Comment by MichaelSimons** [comment]
@tiwarishrijan - Can share the output of `docker version` and `docker info`?  I see `root@...` in your screen shot which gives me the impression you are trying to pull the images from a linux host.  The `mcr.microsoft.com/dotnet/framework/aspnet` images are Windows images and can only be run on a Windows container environment.  If you are looking to run ASP.NET on linux, you would need to use ASP.NET Core.  The ASP.NET Core images are located [here](https://hub.docker.com/r/microsoft/dotnet/).

**Comment by tiwarishrijan** [comment]
@MichaelSimons Thanks, Yes it was Windows Images which i was trying to pull on linux Platform.
