### ISSUE TITLE
Using images in Azure DevOps pipeline not working

### ISSUE THREAD

**Issue by jjindrich** [Microsoft/aspnet-docker#168]
I'm trying to use this images in pipeline. Using this image microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016 in docker build command. Running on hosted server Windows Containers. Task takes too long and fail. Probably images are not cached on server ???

**Comment by jjindrich** [comment]
Getting this error failed to register layer: re-exec error: exit status 1: output: cloning the parent utility VM image failed: SetFileInformationByHandle \\?\C:\ProgramData\docker\windowsfilter\39ca9208d111b3bfd1d8dce31677bb5ca7bc0f284f51646ba62fc1526a7e3f17\UtilityVM\Files\Documents and Settings: The parameter is incorrect.

**Comment by shirhatti** [comment]
Unfortunately, this isn't an ASP.NET specific issue, so we'd be out of our depth trying to answer this.
I'd recommend asking your question in this forum- https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers

FWIW, I think I've seen this issue when I ran out of disk space but that forum would be a better place to ask this question.
