### ISSUE TITLE
data volume in microsoft/aspnet:3.5 error

### ISSUE THREAD

**Issue by rainmakerho** [Microsoft/aspnet-docker#17]
sirs,
i use data volume in microsoft/aspnet ok, but not ok in microsoft/aspnet:3.5 .
will get 0xc037010a error.
The connection with the Virtual Machine hosting the container was closed. ( 0xc037010a)

![aspnetand35compare](https://cloud.githubusercontent.com/assets/11240907/21837318/200c3ef6-d806-11e6-91c1-92a7f1c3c264.png)

**Comment by dnelly** [comment]
Any updates on this issue? I'm having the same problem with microsoft/wcf.

**Comment by shirhatti** [comment]
@rainmakerho Sounds like a point in time issue. Feel free to open a new issue if you're still having issues
