### ISSUE TITLE
microsoft/iis:windowsservercore-1709 is not supported in web app windows container

### ISSUE THREAD

**Issue by hatsengMSFT** [Microsoft/aspnet-docker#173]
Our team is experimenting Web App for (Windows) Container. I got error when trying to upload docker image:

> **Cannot run this Operating System/Version in Windows Containers. Maximum supported OS version is 10.0.14393.9999.**

- How to know the version of *Web App for Windows Container* host OS?
- What is eligible base image os version?
- Our web app can only run with 1709 or later. Does it have a plan to upgrade host OS version?

**Comment by shirhatti** [comment]
Can you share the output of `docker history` for the image you're trying to run?

**Comment by hatsengMSFT** [comment]
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
3925923746cb        2 minutes ago       powershell $env:PATH = 'C:\inetpub\wwwroot\b…   29.9MB
c58215250481        3 minutes ago       powershell #(nop) ADD dir:8c9dd5dc37d8184afd…   2.08GB
534e27e8c7b7        5 minutes ago       powershell #(nop) WORKDIR C:\inetpub\wwwroot    41kB
84c1e9c483fd        5 minutes ago       powershell Start-Process -FilePath "C:/insta…   56.6MB
16eac4af5348        6 days ago          powershell #(nop) COPY dir:687b74af2d79908df…   29.6MB
194ae794a36f        6 days ago          powershell Install-WindowsFeature NET-Framew…   246MB
2ec17d490df9        6 days ago          powershell #(nop)  SHELL [powershell]           41kB
e0eeddf85095        3 weeks ago         cmd /S /C #(nop)  ENTRYPOINT ["C:\\ServiceMo…   41kB
<missing>           3 weeks ago         cmd /S /C #(nop)  EXPOSE 80                     41kB
<missing>           3 weeks ago         cmd /S /C powershell -Command     Add-Window…   261MB
<missing>           3 weeks ago         Install update 10.0.16299.967                   1.85GB
<missing>           17 months ago       Apply image 10.0.16299.15                       4.62GB

**Comment by hatsengMSFT** [comment]
Dockerfile
```
FROM microsoft/iis:windowsservercore-1709

SHELL ["powershell"]

RUN Install-WindowsFeature NET-Framework-45-ASPNET ; \  
    Install-WindowsFeature Web-Asp-Net45 ; \
    Install-WindowsFeature Web-AppInit

# Install Visual C++ runtime for VS 2015 (required by autopilot SDK)
COPY installer "C:/installer"
RUN Start-Process -FilePath "C:/installer/vc_redist.x64.vs2015.exe" -ArgumentList /Install, /Quiet, /NoRestart, /Log, c:\install_logs\vc_redist.x64.vs2015.log -PassThru -Wait; 

WORKDIR /inetpub/wwwroot
ADD "bin\Release\Publish" .

RUN $env:PATH = 'C:\inetpub\wwwroot\bin\MLGWrapper;' + $env:PATH; \
    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine);
```

**Comment by shirhatti** [comment]
Ahh sorry. I just realized I misread your question.

You cannot use a newer container runtime than your host OS version. From the error message I gather you're trying to run a 1709 image on an ltsc2016 host. This is not supported.

Your options here are:
1. Use a newer host OS; OR
2. Run the container with Hyper-V isolation instead.

See https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility for more information

**Comment by hatsengMSFT** [comment]
How to select newer host OS for Web App for Windows container?

**Comment by shirhatti** [comment]
> How to select newer host OS for Web App for Windows container?

This is currently not supported in Azure App Service. You can currently only do this with your own VM.
I'd recommending creating a request for the Azure App Service team at https://feedback.azure.com/forums/169385-web-apps

**Comment by shirhatti** [comment]
Closing this issue as it's not actionable by the ASP.NET team.
