### ISSUE TITLE
You guys broke Swashbuckle/Swagger in the latest version of microsoft/aspnet:4.6.2-windowsservercore-ltsc2016

### ISSUE THREAD

**Issue by Cloudmersive** [Microsoft/aspnet-docker#174]
In the latest version of microsoft/aspnet:4.6.2-windowsservercore-ltsc2016, Swashbuckle no longer works/starts up.

And there is no way to go back to the old version of the image!  Please fix this!

**Comment by shirhatti** [comment]
Could you provide more details on what your issue is?

**Comment by shirhatti** [comment]
> And there is no way to go back to the old version of the image! Please fix this!

Try this
```
docker pull mcr.microsoft.com/dotnet/framework/aspnet:20190108-4.6.2-windowsservercore-ltsc2016
```

See this page for more details https://hub.docker.com/_/microsoft-dotnet-framework-aspnet and this page for a list of all available tags https://mcr.microsoft.com/v2/dotnet/framework/aspnet/tags/list

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.
