### ISSUE TITLE
Tag list has not been updated since January 2019

### ISSUE THREAD

**Issue by msperrin** [Microsoft/aspnet-docker#175]
The tag list is not returning anything after Jan this year, is there a reason tags have not been generated for the last 2 images? Latest pulls an image that's 6 days old.

snippet from https://mcr.microsoft.com/v2/dotnet/framework/aspnet/tags/list showing the last 

    "20190108-3.5-windowsservercore-1709",
    "20190108-3.5-windowsservercore-1803",
    "20190108-3.5-windowsservercore-ltsc2016",
    "20190108-3.5-windowsservercore-ltsc2019",
    "20190108-4.6.2-windowsservercore-ltsc2016",
    "20190108-4.7-windowsservercore-ltsc2016",
    "20190108-4.7.1-windowsservercore-1709",
    "20190108-4.7.1-windowsservercore-ltsc2016",
    "20190108-4.7.2-windowsservercore-1709",
    "20190108-4.7.2-windowsservercore-1803",
    "20190108-4.7.2-windowsservercore-ltsc2016",
    "20190108-4.7.2-windowsservercore-ltsc2019",

**Comment by mbrown555** [comment]
This seems to be an issue with the publishing process which has been transitioned to a new system. We're working on a fix for this months images and this will be resolved for next month. Thanks.

**Comment by shirhatti** [comment]
The February tags were not generated due to an issue in the publishing system. This has been resolved in March and we will continue to publish these tags going forward
