### ISSUE TITLE
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /app/Servicesruntimeconfig.json file specifying the appropriate framework.

### ISSUE THREAD

**Issue by aliridha1510** [Microsoft/aspnet-docker#177]
docker run test:latest
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /app/Servicesruntimeconfig.json file specifying the appropriate framework.

**Comment by shirhatti** [comment]
This repo is for ASP.NET, not ASP.NET Core. Please file your issue at https://github.com/dotnet/dotnet-docker
