### ISSUE TITLE
Docker Hub repo references the wrong github repo

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/aspnet-docker#2]
The [Docker Hub repository](https://hub.docker.com/r/microsoft/aspnet/) associated with the Microsoft/aspnet-docker repository is associated with the wrong github repo.  On the right side of the DH repo there is a Source Repository box.  It contains an [aspnet/aspnet-docker](https://github.com/aspnet/aspnet-docker) hyperlink which references the ASP.NET Core Docker GH repo.  This seems wrong and is confusing.  I would think this should reference [this](https://github.com/Microsoft/aspnet-docker) GH repo.

**Comment by shirhatti** [comment]
@MichaelSimons Microsoft/aspnet on DH originally referred to the ASP.NET Core images for Linux that used the auto-build feature on DH. We have now migrated all ASP.NET Core images to Microsoft/aspnetcore on DH.

I haven't yet been able to figure out how to un-link https://github.com/aspnet/aspnet-docker without deleting and creating the repo on DockerHub which would break existing customers who rely on legacy tags.

**Comment by MichaelSimons** [comment]
Unfortunately, Docker Hub's functionality is limiting in several ways.   I know in the past you used to have to make a request to Docker if you wanted to delete a tag (this is now something an admin can do).  Re-linking a DH repo may be something you have to ask Docker to do for you.

**Comment by natemcmaster** [comment]
Can we try to make some progress on this? We keep getting issues opened on the aspnetcore repo that should belong here.

**Comment by shirhatti** [comment]
Sorry about that. I'll follow up on this.

**Comment by natemcmaster** [comment]
Any progress?

**Comment by shirhatti** [comment]
I've asked around in Docker slack channel and it turns out DockerHub has no way for us to do that short of **deleting and re-creating the repo**. Given the DockerHub persists all the intermediate layers from every build. We run a  risk of breaking people who are relying any older or intermediate images including those we might even have untagged.

If @Eilon and @HongGit are okay with this approach, we can put together a concrete plan for following through with this.

**Comment by Eilon** [comment]
I... have no opinion on this 😄

**Comment by HongGit** [comment]
The approach should include plans to help people who might be broken.

**Comment by natemcmaster** [comment]
FYI - we're continually getting people posting issues on aspnet/aspnet-docker. Had another issue opened today that should have been on this repo.

**Comment by MichaelSimons** [comment]
This issue has been addressed.  Docker was able to fixup the link for us!
