### ISSUE TITLE
asp-net docker file missing script execute to enable dns.

### ISSUE THREAD

**Issue by christophedemey** [Microsoft/aspnet-docker#22]
Hi

Concerning this file : https://github.com/Microsoft/aspnet-docker/blob/master/4.6.2/Dockerfile
Problem : When using docker-compose with this image and a db sql developer image my website cannot resolve the db dns in my connectionstring.
Solution :
Added this at the end of the file :
RUN powershell set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord

Now the dns is being resolved correctly.
I hope this gets added and helps someone not spend hours of googeling ;-)

**Comment by shirhatti** [comment]
@Jinhuafei Thoughts?

**Comment by Jinhuafei** [comment]
This has nothing to do with asp.net. Looks like same issue as [this one](https://github.com/docker/docker/issues/31093). The fix/workaround should be added to the base windows image, cuz this is not aspnet image specific.

**Comment by shirhatti** [comment]
Thanks for catching that! We can leave this issue as we await a fix downstream.

@christophedemey Thanks for the suggestion, but we'd rather not add temporary workarounds into our layer, especially given that the known workaround is easy to implement

**Comment by shirhatti** [comment]
This issue has been fixed according to https://github.com/moby/moby/issues/31093#issuecomment-296852851
