### ISSUE TITLE
unable to pull microsoft/aspnet-docker

### ISSUE THREAD

**Issue by AaronVanderwielen** [Microsoft/aspnet-docker#25]
The image pulls, appears to finish, and then the 4GB part retries after appearing to finish, and just keeps doing that until the host closes connection.

![image](https://cloud.githubusercontent.com/assets/6758730/25548669/7a0ddb92-2c22-11e7-9305-fef4337d2f22.png)

I saw that someone else noticed this issue in a separate thread here: https://github.com/aspnet/aspnet-docker/issues/228
Was just checking if anyone knew what was going on.

**Comment by FFLSH** [comment]
As these are Windows images, your Docker host will need to be set to run Windows containers. If you right-click the Docker whale in your task tray and click 'Switch to Windows containers' this may alleviate your problem.

**Comment by shirhatti** [comment]
@AaronVanderwielen Feel free to re-open if you're still seeing this issue
