### ISSUE TITLE
Documented 4.6.2 tags are out of date

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/aspnet-docker#30]
The documented tags in the readme for 4.6.2 seem out of date.

`4.6.2-windowsservercore-10.0.14393.321, 4.6.2-windowsservercore, 4.6.2, latest (4.6.2/Dockerfile)`

The `4.6.2-windowsservercore-10.0.14393.321` tag is out of date.  `4.6.2-windowsservercore-10.0.14393.1198` is the most recent fully versioned tag. It is also inconsistent that the `windowsservercore` tags are included for 4.6.2 but not for 3.5.

**Comment by shirhatti** [comment]
Fixed
