### ISSUE TITLE
"The directory name is invalid" with the latest image

### ISSUE THREAD

**Issue by MichaelLogutov** [Microsoft/aspnet-docker#32]
Using microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.1358 image I've got this error when launching site that was previously running fine:
```
Compiler Error Message: CS0016: Could not write to output file 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\ab2094c7\6e6df95\App_global.asax.wz646n9b.dll' -- 'The directory name is invalid. '
```

I thinks it's permission issue

**Comment by shirhatti** [comment]
cc @HongGit @mcy94w

**Comment by HongGit** [comment]
@MichaelLogutov could you please share your repro steps?  Did you just simply migrate your application to the new ASP.NET 4.6.2 image?  Was there any operations performed before your migration?

**Comment by MichaelLogutov** [comment]
Ok. False alarm. But if anyone encountered this error - it's because I've removed Microsoft.CodeDom.Providers.DotNetCompilerPlatform package. In that case the error a bit missleading - it tries to "compile" global.asax but can't (needed c# 6 - dunno why) and falling with this strange error.
