### ISSUE TITLE
docker run prints 'Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"'

### ISSUE THREAD

**Issue by FFLSH** [Microsoft/aspnet-docker#34]
When performing `docker run -i microsoft/aspnet` the following line is printed ~50 times:

`Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"`

This appears to have no effect on functionality, but leaves undesirable spam in the logs of that container

`docker version`:

Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false

Windows Server Core 2016

**Comment by shirhatti** [comment]
Known. `ServiceMonitor.exe` shells out to `appcmd.exe` to promote environment variable set through docker -e and make it available to your application running as the IIS DefaultAppPool. We're making a change to only promote Environment variables explicitly added by a user and create an exclusion list for everything that exists by default. This change should reduce the output you see from appcmd.exe

**Comment by lushare** [comment]
i thank you use ”appcmd.exe“ create site。you have to commit you configure

**Comment by shirhatti** [comment]
Tracking this issue here https://github.com/Microsoft/IIS.ServiceMonitor/issues/6
