### ISSUE TITLE
Can't start service - Lanmanserver on aspnet container

### ISSUE THREAD

**Issue by timothies** [Microsoft/aspnet-docker#36]
I've created an empty container FROM microsoft/aspnet. when I connect to it ('docker exec -it *containerId* powershell')  and try to start the service Lanmanserver I get the following error.

(Note  I've attached the dockerfile/start script [which just sleeps to keep the container running.)

PS C:\> start-service lanmanserver
start-service : Failed to start service 'Server (lanmanserver)'.
At line:1 char:1
+ start-service lanmanserver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

[Blank Container.zip](https://github.com/Microsoft/aspnet-docker/files/1104155/Blank.Container.zip)

**Comment by shirhatti** [comment]
@PatrickLang Is `lanmanserver` supported in containers?

**Comment by PatrickLang** [comment]
No, it's not. Containers can only connect to SMB shares, not host them
