### ISSUE TITLE
Latest version fails to start website from VS

### ISSUE THREAD

**Issue by tegaaa** [Microsoft/aspnet-docker#39]
I downloaded the latest microsoft/aspnet and microsoft/windowsservercore and when I start and app from visualstudio which used to work without any issue it now fails with an access denied to some aspnet temp folder.  I scramble to get this working and reverted back to using image microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.1198 which where the version that worked.  I'm not sure if it's a update to core 1358 or the installation of .net 4.7 or a combination of both.  To repro it's really simple just do a file new aspnet project add docker support from vs then make sure that the microsoft/aspnet is the latest one and click run.  It should fail.  If you download 4.6.2-windowsservercore-10.0.14393.1198 and change the dockerfile to use that one it works fine.

**Comment by shirhatti** [comment]
@tegaaa I'm aware of the issue. It's because of a change to ServiceMonitor.exe that we introduced in June.
We have a pending PR https://github.com/Microsoft/aspnet-docker/pull/41 that should address this issue if you want to try it out

**Comment by tegaaa** [comment]
I'm not sure it has to do with ServiceMonitor.exe it's a read-only error, can't copy a dll to the ASPNET temp folder.  The error also mentioned the fact that the apppool user might not have permissions to write to the temp location.

**Comment by shirhatti** [comment]
We added a feature to ServiceMonitor.exe to allow you to flow Environment variables from `docker run -e ...` all the way to your application. The way we achieved this is by promoting environment variables set on the entrypoint process to the DefaultAppPool. While doing so, we didn't guard against promoting environment variables from the user profile of the entrypoint process. In your case, the `TEMP` variable for the AppPool is being changed to that of the EntryPoint process which runs under a different identity (ContainerAdministration). Hence NTFS permissions prevent the AppPool identity prevent from writing to the TEMP directory ACLed to the ContainerAdministrator which is required for view compilation.

**Comment by tegaaa** [comment]
Ok. But that breaks all vs integration? Or is there something we need o do in the dockerfile to make this work?

Also on top of having the permission error the vs debugger is not attaching to the run apppool it give a weird error. I don’t have it handy but using the tag I mentioned preciously everything works.  Something is really odd with this latest build

Sent from my Windows 10 phone

**Comment by shirhatti** [comment]
This is been fixed in the 10.0.14393.1480 (July) updates
