### ISSUE TITLE
w3svc error

### ISSUE THREAD

**Issue by colmprunty** [Microsoft/aspnet-docker#43]
I am getting the following error when deploying a container to a Windows Server 2016 instance on AWS:

`ERROR: Failed to stop or quesry status of service 'w3svc' error [800705b4]`

This seems to be a similar issue to [this one](https://github.com/Microsoft/iis-docker/issues/47) on the IIS dockerfile (the giveaway is "quesry"), but this image runs Service Monitor itself so I think it's relevant to both.

Interestingly, this only occurs when the server has been newly created and started up for the first time. Any attempt after the initial deployment has been successful. 

This error has only appeared after changing our dockerfile from 
`FROM microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.1358`
to
`FROM microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.1480`

**Comment by shirhatti** [comment]
Just a cursory look at the code and it looks like the call to `StartService` is timing out. This is something we don't observe in the happy path. So I suspect, there is something you are doing while building your container that's causing w3svc to fail to start. Can you share your Dockerfile?

cc @mcy94w @pan-wang

**Comment by colmprunty** [comment]
Thanks for getting back to me, the Dockerfile looks like this:

```
FROM microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.1480
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

ENV APPLICATION_NAME="MyAppName"

RUN Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter 'system.applicationHost/log' -name 'centralLogFileMode' -value 'CentralW3C'; \
    Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter 'system.applicationHost/log/centralW3CLogFile' -name 'period' -value 'Hourly'; \
    Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter 'system.applicationHost/log/centralW3CLogFile' -name 'directory' -value "%SystemDrive%\iislogs\$env:APPLICATION_NAME"; \
    Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter 'system.applicationHost/log/centralW3CLogFile' -name 'logExtFileFlags' -value 'Date, Time, ClientIP, UserName, SiteName, ComputerName, ServerIP, Method, UriStem, UriQuery, HttpStatus, Win32Status, BytesSent, BytesRecv, TimeTaken, ServerPort, UserAgent, Referer, ProtocolVersion, Host, HttpSubStatus'; \
    iisreset

COPY output C:/inetpub/wwwroot/

# Run IIS config tool
RUN & "C:\inetpub\wwwroot\$env:APPLICATION_NAME.IIsConfigTool\$env:APPLICATION_NAME.IisConfigTool.exe"

# Clean up config tool
RUN & "rm C:\inetpub\wwwroot\$env:APPLICATION_NAME.IIsConfigTool\ -r"

HEALTHCHECK --interval=20s --timeout=10s --retries=10 CMD powershell -command \
	try { \
     $response = iwr http://healthcheckurl -UseBasicParsing; \
     if ($response.StatusCode -eq 200) { return 0} \
     else {return 1}; \
    } catch { return 1 }
	
COPY ./docker-entrypoint/* C:/inetpub/wwwroot/

WORKDIR "C:/inetpub/wwwroot"

ENTRYPOINT ["Powershell", "./docker-entrypoint.ps1"]
```

And the Powershell file called at the end looks like this:

```
$ErrorActionPreference = 'Stop'

.\script1.ps1
.\update-config.ps1
.\script3.ps1

C:\ServiceMonitor.exe w3svc
```

I've reverted back to .1358 and it's working fine again.

**Comment by shirhatti** [comment]
Can you share this docker image? Either by pushing to a registry or  by emailing me a link. There is nothing immediately apparent, but we really want to take a closer look at it.

**Comment by colmprunty** [comment]
I can't share the image, I'm afraid, it's work stuff.

**Comment by shirhatti** [comment]
Given that it fails while attempting to start up, it probably has nothing to do with your app contents. it's something you're doing in either `$env:APPLICATION_NAME.IisConfigTool.exe` or one of your PowerShell scripts.
Could you try working your way down to a minimal repro that you can share?

Another thing that might give us a clue is your final `applicationHost.config` just before you attempt to run ServiceMonitor.

**Comment by shirhatti** [comment]
@colmprunty Please re-open if you can share your `applicationHost.config` or a minimal repro?

**Comment by samiraguiar** [comment]
@colmprunty Did you ever manage to fix it?
I'm facing this issue right now.

**Comment by colmprunty** [comment]
Yeah as I said initially, I only had this problem on a newly created server on the first run, but that wasn't much use for autoscaling. I think I stayed on 1358, but I'll check when I get into work tomorrow.

**Comment by samiraguiar** [comment]
@colmprunty thanks for getting back. I'm using later versions and sometimes when starting a container I get that error. So this is probably related to Windows updates, like you said, though I don't know which.

**Comment by eolamisan** [comment]
Just noticed I'm also having this issue randomly.

**Comment by liberdis** [comment]
ERROR: Failed to stop or query status of service 'w3svc' error [800705b4]

I'm confused as to why this is closed. I started getting this error about a month ago (dec 2018) inconsistently - about one in every 5 starts. I'm using microsoft/aspnet:4.7.2-windowsservercore-ltsc2016

**Comment by AndreyBespamyatnov** [comment]
Have the same issue for `mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019` when I'm using that command `docker-compose up -d --force-recreate --remove-orphans`
