### ISSUE TITLE
Changing shell also affects derived images

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/aspnet-docker#44]
Commit https://github.com/Microsoft/aspnet-docker/commit/6f15ac6c51872c30bb94436b6d12c1622ca9f7f7 added the following to Dockerfiles:

```
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
```

This sets a non-default shell (the default being cmd.exe). This may be unexpected by derived images that expect the shell to be cmd.exe. Upgrading to the latest image broke some of our derived images due to this. It would be "nicer" if these base layers did not customize the shell, just to avoid surprises.

**Comment by shirhatti** [comment]
Agreed. Unfortunately, reverting it would result in another breaking change since we've made this change 3 months ago.
We definitely plan to not customize the shell any further.
