### ISSUE TITLE
Can docker image support .NET 2.0

### ISSUE THREAD

**Issue by yotewach** [Microsoft/aspnet-docker#45]
Hi can you build the image that support the ASP.NET V2 because current we have support this version but i can find any image on NET 2.0

**Comment by shirhatti** [comment]
I'm assuming you're talking about .NET Framework, in which case you should the ASP.NET 3.5 image since the 3.5 Framework was an in-place update for 2.0.

If you meant ASP.NET **Core** 2.0, checkout https://github.com/aspnet/aspnet-docker
