### ISSUE TITLE
Documentation still outdated for site_root arg

### ISSUE THREAD

**Issue by red8888** [Microsoft/aspnet-docker#48]
This issue was filed like 10 months ago: https://github.com/Microsoft/aspnet-docker/issues/11

The docs are _still_ outdated. The main page has this under "how to use these images": 
`docker build -t aspnet-site --build-arg site_root=/ .`

Would be an easy fix to save people some time from googling the error and being directed to the github issue i linked to above.

**Comment by shirhatti** [comment]
This has already been addressed.
