### ISSUE TITLE
Remove the contents of the default IIS site from the ASP.NET base image

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/aspnet-docker#5]
Having multiple websites running per container is an anti-pattern and should be avoided. Deleting the default website would a best practice.

**Comment by HongGit** [comment]
Do you mean to delete the default web site?  We should keep the default web site, and let the user/customer to move/create their web applications.

**Comment by shirhatti** [comment]
We can simplify what the end user’s Dockerfile will look like.

Old Dockerfile
```
FROM microsoft/aspnet
RUN mkdir C:\aspnet
RUN powershell -NoProfile -Command \
    Import-module IISAdministration; \
    New-IISSite -Name "ASPNET" -PhysicalPath C:\aspnet -BindingInformation "*:8000:"

EXPOSE 8000
ADD .   /aspnet
```
After changes, new Dockerfile

```
FROM microsoft/aspnet
ADD .   /inetpub/wwwroot
```
