### ISSUE TITLE
The library 'libhostpolicy.so' required to execute the application was not found

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/aspnet-docker#52]
I'm not certain where to post this issue. I get the following error when running one of two docker containers using the ASP.NET Core 2.0 linux image:

```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app'.
```

The container runs fine when being run using Visual Studio's Docker Support project. It only throws the above error when running on Docker for AWS which uses Moby linux for the host OS.

I get no further information than that unfortunately. I'm not sure how to debug it further either. Looking online, I've seen people mention that I need a `runtimeconfig.template.json` file  which already I have.

**Comment by shirhatti** [comment]
This issue was moved to aspnet/aspnet-docker#301

**Comment by RickStrahl** [comment]
Seeing this as well. I'm trying to run an app that runs fine on from the Publish folder. It fails both in the Bash shell and in a docker container.

In the Windows Bash shell I can `dotnet run` and the app runs. But when I publish and cd into the publish folder and then run `dotnet <myMainDll>` I get the error:

> A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/var/www/WestwindGlobalization/'.

Now this app is a ported old app, so my guess here is it has to do with Linux incompatible paths somewhere, but that's just a guess. But it is very odd that it work using `dotnet run` but not directly running hte publish output.

**Comment by RehanSaeed** [comment]
@RickStrahl I feel your pain, I was banging my head against the wall on this error for a while. This issue was moved to https://github.com/aspnet/aspnet-docker/issues/301, in it I mention that this error went away for me but I'm not certain why or what I changed to make it so.

**Comment by janvorli** [comment]
@RickStrahl could you please run it with shared library linker debugging on to see where it tries to look for the library like this:
```sh
LD_DEBUG=files dotnet <myMainDll>
```
and then share the output e.g. using gist (it is quite extensive)? That should help us to pinpoint why the library was not located.
