### ISSUE TITLE
ASP.NET layers not flagged as "foreign"

### ISSUE THREAD

**Issue by sixeyed** [microsoft/aspnet-docker#53]
Seeking clarification on this. I build an image based on `microsoft/aspnet:3.5-windowsservercore-10.0.14393.1715`, tag it and push to a private registry. The two Windows Server base layers are not pushed (they're foreign layers), but the next three layers from the ASP.NET image are pushed. These total 3.7GB:

![aspnet-foreign-layers](https://user-images.githubusercontent.com/157413/31166662-6f91f68e-a8e7-11e7-8d81-1c3c8160d342.JPG)

In the ASP.NET image the 3.5 framework is added from a local CAB, so users can't reproduce those layers for themselves. Should they also be flagged as foreign layers so users aren't pushing them to their own registries?

**Comment by shirhatti** [comment]
Duly noted and definitely worth exploring.
I'm not familiar with what the guidance is for whether something should be marked as a foreign layer or not. Is this something that's already well defined?

**Comment by HongGit** [comment]
@richlander any thoughts?

**Comment by MichaelSimons** [comment]
My understanding is the Windows OS layers are foreign layers because the Windows licensing requires them to be hosted by Microsoft servers.  The .NET products do not have these constraints therefore they are contained in "normal" layers and can be hosted on any registry.

**Comment by HongGit** [comment]
@sixeyed hope this answers your question.
