### ISSUE TITLE
DLL Not found C:\Windows\Microsoft.Net\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll

### ISSUE THREAD

**Issue by pradley** [Microsoft/aspnet-docker#58]
When using my asp.net application inside of a docker container it says the specified module could not be found and errors out.
When I docker exec into the container and cd to the path above I do actually find the DLL.

![image](https://user-images.githubusercontent.com/9398978/31960317-3c438692-b8ac-11e7-988d-210f71a5bd04.png)

I have no idea what the problem is or why it cant load a file that is actually there. Any help would be nice. Thanks in advance

**Comment by Jinhuafei** [comment]
Please try latest image.

https://github.com/Microsoft/dotnet-framework-docker/issues/96
