### ISSUE TITLE
The ASP.NET 3.5 image needn't enable ASP.NET 4.6.2

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/aspnet-docker#6]
These [lines](https://github.com/Microsoft/aspnet-docker/blob/master/3.5/Dockerfile#L7-L8) can be omitted from the Dockerfile

**Comment by shhsu** [comment]
Fixed with 
https://github.com/Microsoft/aspnet-docker/commit/be2d95611b234cce4a7934fb34706435787ca5a3
