### ISSUE TITLE
Add support for building ASP.NET applications with Docker

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/aspnet-docker#63]
Microsoft should produce Docker images that can be utilized to build ASP.NET applications.

**Comment by MichaelSimons** [comment]
Depends on https://github.com/Microsoft/dotnet-framework-docker/issues/38

**Comment by juliolima86** [comment]
Now depends on Microsoft/dotnet-framework-docker#37
I'm expecting this image to build asp.net framework and modernize then.

**Comment by MichaelSimons** [comment]
Issue moved to [Microsoft/dotnet-framework-docker #103](https://github.com/Microsoft/dotnet-framework-docker/issues/103) via [**ZenHub**](https://www.zenhub.com/)
