### ISSUE TITLE
Docker Read-Only File System

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/aspnet-docker#66]
I learned that you have the ability to set the file system to [read-only](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v-read-only) in docker by setting a simple boolean flag. Any custom volumes you've specified remain unaffected. This seems like a great little flag to turn on for some added security, so I tried it out and got the following error from my ASP.NET Core 2.0 runtime image:

> Failed to initialize CoreCLR, HRESULT: 0x80004005

Does the ASP.NET Core image support this feature and could it even be turned on in the Dockerfile by default for some added security?

**Comment by richardgavel** [comment]
I don't see anything that suggests this is something that goes in the Dockerfile, just a container runtime feature. Now it's possible that CoreCLR has code within it that tries to open files in a non-read-only mode...

**Comment by shirhatti** [comment]
This could possibly be achieved by specifying volume mounts corresponding to every directory that ASP.NET and your application may write temporary write files to.

@RehanSaeed if you want to give it a shot, we can help you through issues you encounter along the way.

@csharpfritz and @HongGit what are your thoughts on this?

**Comment by RehanSaeed** [comment]
Typical ASP.NET Core apps don't use any temporary directories that I'm aware of. Volume mounts should work but I don't know which directories .NET Core needs write access to.

**Comment by shirhatti** [comment]
Ah sorry. This is the repo for ASP.NET, not ASP.NET Core. You're probably looking for https://github.com/aspnet/aspnet-docker

**Comment by RehanSaeed** [comment]
Moved to https://github.com/aspnet/aspnet-docker/issues/331
