### ISSUE TITLE
Add support for installing msi packages that depend on oledlg.dll

### ISSUE THREAD

**Issue by ktsangop** [Microsoft/aspnet-docker#68]
After a long research and experimentation, while trying to install Crystal Reports Runtime for .NET, i have found out that the installation package depends on oledlg.dll.

As described here in more detail, this DLL file is not included on the Windows Server Core container : 
[Windows 2016 container and Crystal Reports Runtime]
(https://social.msdn.microsoft.com/Forums/sqlserver/en-US/20588e86-c8fa-450a-8dad-77484eb9ef39/windows-2016-container-and-crystal-reports-runtime?forum=windowscontainers)

So in order to be able to install Crystal Reports, in any of the docker containers based on Windows Server Core, you need to manually extract oledlg.dll, from a full Windows Server machine, and copy it on your docker container. 
After that, you should be able to install this specific package, and probably any other package that depends on that DLL.

Now, i would love to create a public repository, specific for users that need Crystal Reports support, but i i am not sure if i can upload a signed DLL from Microsoft in a public repository.

So, is there a way to overcome this issue, without the above 'hack', and without violating copyright?

My suggestion would be to include oledlg.dll in the Windows Server Core based containers, but i am sure that there is a reason for it not being already there.

Thanks in advance.

**Comment by HongGit** [comment]
@shirhatti can you please route this to the right team?

**Comment by shirhatti** [comment]
This should now be possible via the new Windows base image- https://hub.docker.com/_/microsoft-windowsfamily-windows

Please re-direct support requests to https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers
