### ISSUE TITLE
Update Dockerfiles to use COPY instruction rather than ADD

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/aspnet-docker#72]
To conform with [Dockerfile best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy), the COPY instruction is preferred over ADD.  All Microsoft Dockerfiles should be following the best practices as they are often referred upon and copied.

Related to https://github.com/Microsoft/dotnet-framework-docker/issues/45

**Comment by HongGit** [comment]
I have scanned all DockerFiles, and find that all COPY commands are replaced with ADD.

**Comment by MichaelSimons** [comment]
@HongGit - not sure I understand your comment.  The recommendation is to use `COPY`, not `ADD`.

**Comment by HongGit** [comment]
@MichaelSimons my bad.  I will fix that.

**Comment by HongGit** [comment]
This has been fixed in PR#85.
