### ISSUE TITLE
Consider setting the backtick as the escape character in the Dockerfiles

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/aspnet-docker#73]
Using the backtick as the escape character in Windows based Dockerfiles has several advantages.  See the [Dockerfile Reference](https://docs.docker.com/engine/reference/builder/#escape) for details.  While it is not necessary, I believe it would be beneficial for Microsoft Dockerfiles to use the backtick escape character over the default backslash since they are often referenced and copied by many users.  Using the backtick will reduce the chances of users encountering unintentional issues (e.g. `COPY testfile.txt c:\`)

This is already being used in the .NET Core Docker repos.

Related to https://github.com/Microsoft/dotnet-framework-docker/issues/46

**Comment by shirhatti** [comment]
Do we need to explicitly set this or will this be inherited from the dotnet framework images?

**Comment by MichaelSimons** [comment]
`ESCAPE` is a Dockerfile directive and doesn't impact the image therefore it needs to be explicitly set.  

Note: This is why it acceptable to make this change - it won't affect any Dockerfiles that are based on the microsoft/aspnet images.

**Comment by HongGit** [comment]
This has been fixed in PR#85.
