### ISSUE TITLE
ltsc2016 based Dockerfiles should use a tag in the FROM that explicitly indicates ltsc2016

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/aspnet-docker#74]
Currently the 4.7.1 ltsc2016 based Dockerfile uses the following FROM

`FROM microsoft/dotnet-framework:4.7.1`

The `microsoft/dotnet-framework:4.7.1` tag is a manifest backed tag therefore the Windows version the image is based on is ambiguous.  It would arguably be better to use a tag that explicitly calls out the Windows Server version (e.g. microsoft/dotnet-framework:4.7.1-windowsservercore-ltsc2016).  This would also make the ltsc2016 based Dockerfiles consistent with the 1709 base Dockerfiles.

This change should be applied to all ltsc2016 Dockerfiles.

**Comment by HongGit** [comment]
This has been fixed in PR#85.
