### ISSUE TITLE
Windows defender/update issues

### ISSUE THREAD

**Issue by westmatte** [microsoft/aspnet-docker#76]
Hello! I'm not sure if this is just me having this issue, or if it is for everyone. I'm creating an ASP.NET Web API in a Docker Container for Windows that uses Windows defender to scan incoming files, but using this image I'm not able to use windows defender. My stackoverflow issue for more details: 

https://stackoverflow.com/questions/47625152/windows-defender-update-issues-when-running-inside-windows-docker-container-wind 

Do you happen to know why this is, and if it's a problem with my setup or something with the image? Thank you!

**Comment by HongGit** [comment]
@PatrickLang is windows defender turned enabled in the base image?

**Comment by artisticcheese** [comment]
Yes, it's enabled, and it can not be turned off since it requires reboot to be uninstalled
