### ISSUE TITLE
Building image fails at ADD ServiceMonitor.exe /

### ISSUE THREAD

**Issue by veaceslc** [Microsoft/aspnet-docker#77]
When running docker build -t aspnet-site --build-arg site_root=/ .

build fails at step 4:
Step 4/8 : ADD ServiceMonitor.exe /
ADD failed: GetFileAttributesEx \\?\C:\Windows\TEMP\docker-builder514299249\ServiceMonitor.exe: The system cannot find the file specified.

Windows Server 2016 Version 1607 Build 14393.447
Docker Version 17.09.0-ce-win33 (13620)

Any ideas?

**Comment by mcy94w** [comment]
Did you have the service monitor side by side with your dockerfile

**Comment by MichaelSimons** [comment]
ServiceMonitor.exe is now downloaded.  See https://github.com/Microsoft/aspnet-docker/pull/88.  @veaceslc - please try the latest Dockerfiles.  Closing but feel free to log a new issue if you have issues with the latest Dockerfiles.
