### ISSUE TITLE
ServiceMonitor.exe should be a downloaded asset.

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/aspnet-docker#78]
The ServiceMonitor.exe should be downloaded within the Dockerfile instead of copied from the build context.  The following are reasons to do this.

1. It is currently copied within 6 different locations within the repo.  This number will soon grow with #67.
2. Pulling the resource from a public URL will allow anyone to easily duplicate the ASP.NET Dockerfiles as needed.  There are several scenarios which users may not be able to use the ASP.NET images (e.g. they need to base their Dockerfile on a different base image yet they need ASP.NET support).

One possible place to host this content would be https://dotnetbinaries.blob.core.windows.net/dockerassets.  This is used to host other content needed by the various .NET Dockerfiles.

**Comment by shirhatti** [comment]
This issue was moved to Microsoft/IIS.ServiceMonitor#17

**Comment by MichaelSimons** [comment]
@shirhatti - This repo still needs an active issue to update the updates to download/install ServiceMonitor.exe.  In other words it needs to consume the result of Microsoft/IIS.ServiceMonitor#17.

**Comment by MichaelSimons** [comment]
Fixed with https://github.com/Microsoft/aspnet-docker/pull/88
