### ISSUE TITLE
Missing version-specific tags

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/aspnet-docker#81]
The December batch of images appears to be missing the version-specific/KB-specific tags that allow a specific Windows base image to be targeted (e.g. `4.7.1-windowsservercore-1709_KB4048955` or `4.7.1-windowsservercore-10.0.14393.1884` from November).

If this is not intentional, please add them once more.

**Comment by HongGit** [comment]
@mcy94w can you please comment?

**Comment by mcy94w** [comment]
Hi @sandersaares:

We no longer publish version-specific tags anymore. For details. Please check this document.

https://github.com/dotnet/announcements/issues/38
