### ISSUE TITLE
Include full Windows version in Docker image tags

### ISSUE THREAD

**Issue by sixeyed** [microsoft/aspnet-docker#83]
Previous releases of the images had a tag which suffixed the Windows release they were based from, e.g. `microsoft/aspnet:4.7.1-windowsservercore-10.0.14393.1884`. These long tags are a bit cumbersome but they're idempotent and explicit about what the image is based on, so you can ensure everyone is on the same base image.

New releases are using a more generic tag, eg. `microsoft/aspnet:4.7.1-windowsservercore-ltsc2016` which looks like it is **not** idempotent, so this month's `-ltsc2016` image will be different from next month's, even though they have the same tag.

Two issues with this:

- different environments can be using different base ASP.NET versions without realising, as they have the same image tag

- when you build a dependent image it will use the most recent version of `-ltsc2016` so then your app images are no longer idempotent. If I want to repro a production issue, my local app image - built from the same Dockerfile as production - will have a different set of Windows KBs installed, and I won't know what's in there.

**Comment by MichaelSimons** [comment]
@sixeyed - The topic of idempotent tags is one that I struggle with.  As I look around the Docker community it seems far more often the tags aren't idempotent.  What I would consider the normal pattern is `openjdk:8u151-jre-stretch`, this isn't idempotent as it doesn't identify the specific OS version the image is based on.  `microsoft/aspnet:4.7.1-windowsservercore-ltsc2016` aligns with this pattern.  Digest's certainly aren't readable but they seem like the only true was to guarantee idempotency.

cc @richlander
