### ISSUE TITLE
readme.md issue

### ISSUE THREAD

**Issue by AceHack** [Microsoft/aspnet-docker#84]
Doc says

> Note: Multi-arch tags, such as 4.7.1, have been updated to use nanoserver-1709 images if your host is Windows Server 1709 or higher or Windows 10 Fall Creators Update (Version 1709) or higher. You need Docker 17.10 or later to take advantage of these updated tags.

As far as I can tell this is not true, it's using server code 1709.  Thanks.

**Comment by MichaelSimons** [comment]
Resolved with https://github.com/Microsoft/aspnet-docker/pull/90.
