### ISSUE TITLE
Permission denied for App_Data

### ISSUE THREAD

**Issue by osoftware** [Microsoft/aspnet-docker#93]
I'm struggling with allowing the ASP.NET app to write to App_Data folder. I get UnauthorizedAccessException.
The Dockerfile is as follows:
```
FROM microsoft/aspnet:4.6.2
ARG source
WORKDIR /inetpub/wwwroot
COPY ${source:-obj/Docker/publish} .
RUN echo y | cacls App_Data /G IIS_IUSRS:F
```
The last line was my attempt to grant permissions. This works when I exec it on a running container but this seems to not affect anything when used as above.

What is the proper way of granting the read-write access to App_Data? Why doesn't it work out of the box?

**Comment by HongGit** [comment]
@mcy94w could you please take a look?

**Comment by mcy94w** [comment]
@osoftware  Can you `try Set-Acl`  powershell command instead using cacls?

**Comment by osoftware** [comment]
I ended up using `icacls` instead of `cacls`.
