### ISSUE TITLE
4.7.1 Images do not have .NET Framework 4.7.1 Installed

### ISSUE THREAD

**Issue by jonstelly** [Microsoft/aspnet-docker#95]
.NET 4.7.1 applications will not run in the LTSC2016 docker image that claims to have .NET Framework 4.7.1.  Checking the registry it looks like only .NET 4.6.2 is installed there.  This is the image `da1d0ce1ede4` listed below.

I first noticed that a web app I was building/deploying was generating a runtime error... but then I tried to mount a volume and run a very simple .NET 4.7.1 'Hello World' console app, and it fails to run.  The same console app runs using the microsoft/dotnet-framework docker image.  I have verified that I've got the latest images downloaded, and this is happening on both my machine and our servers with images built on our CI agents.

Docker images:

```
microsoft/aspnet                   4.7.1                              da1d0ce1ede4        44 hours ago        14.2GB
microsoft/aspnet                   4.7.1-windowsservercore-ltsc2016   da1d0ce1ede4        44 hours ago        14.2GB
microsoft/aspnet                   latest                             da1d0ce1ede4        44 hours ago        14.2GB
microsoft/aspnet                   4.7.1-windowsservercore-1709       d8d76b1eb867        2 days ago          7.65GB
microsoft/dotnet-framework         latest                             4cf507015e2b        2 days ago          12.7GB
```

Command: `docker run -it --rm --entrypoint powershell microsoft/aspnet`

```
PS C:\> gci 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\'


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full


Name                           Property
----                           --------
1033                           CBS           : 1
                               Install       : 1
                               Release       : 394802
                               Servicing     : 0
                               TargetVersion : 4.0.0
                               Version       : 4.6.01586
```

While on the dotnet-framework image

Command: `docker run -it --rm --entrypoint powershell microsoft/dotnet-framework`

```
PS C:\> gci 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\'


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full


Name                           Property
----                           --------
1033                           CBS           : 1
                               Install       : 1
                               Release       : 461310
                               Servicing     : 0
                               TargetVersion : 4.0.0
                               Version       : 4.7.02558
```

I verified the dotnet framework versions using [this page](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed).

**Comment by sandersaares** [comment]
I confirm my builds are also broken by this defect.

**Comment by jonstelly** [comment]
This appears to have been fixed with the new images pushed 3 days ago.  I switched back to aspnet:latest and everything seems fine.

I find it a bit disappointing there was no comment/triage on this card in a week but at least it's fixed.

**Comment by mcy94w** [comment]
This issue has been fixed on April/10.
