### ISSUE TITLE
aspnet:4.7.1-windowsservercore-ltsc2016 doesn't actually have dotnet 4.7.1 installed

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/aspnet-docker#96]
@Spotypop commented on [Tue Apr 17 2018](https://github.com/Microsoft/dotnet-framework-docker/issues/119)

We are using microsoft/aspnet:4.7.1-windowsservercore-ltsc2016 image.
In last couple of days seems like some changes were made to the image and now it lacks dotnet 4.7.1

**Comment by HongGit** [comment]
@Spotypop I pulled down the latest microsoft/aspnet:4.7.1-windowsservercore-ltsc2016 image, and verified that the binaries in the image are .NET 4.7.1 binaries.  

Can you please elaborate more on why you say that it lacks dotnet 4.7.1?
