### ISSUE TITLE
ASP.NET and .NET Core hosting bundle

### ISSUE THREAD

**Issue by jmajoor** [Microsoft/aspnet-docker#98]
There is a docker image for ASP.NET Core and there is this docker image for ASP.NET 4.7.1.
Is there an image that has ASP.NET 4.7.1 and the .NET Core Hosting Bundle?
We have a application that has several services and some of them have been migrated to ASP .NET Core while others are still on ASP.NET and an image with the combination would be very useful.

I know I can install the hosting bundle as part of my own image, but installing the hosting bundle results in a 650Mb layer and I would rather avoid having that as part of my image. (don't mind the size if it is part of a Microsoft base image).

When I look how ASP.NET Core builds their image, then I see they are not using an installer but download some zip file and just expand the archive. There is however no such zip file for the hosting bundle that I know of (not sure whether the unzip will lead to a smaller image).
Is there a better way of getting the hosting bundle installed without creating such a large layer?

Ideally I would like a Microsoft image that I can use as the base of my image that has both ASP.NET and the core hosting bundle installed. 
Is this a request that you would consider?

**Comment by shirhatti** [comment]
Unfortunately, we have no plans to introduce a new base image that includes the server hosting bundle. For now, your best bet remains to install the server hosting bundle yourself.

The ASP.NET Core image that you're referencing directly expands the runtime store archive as opposed to installing the shared hosting bundle. The only appreciable savings in size in that image would arise from the fact that Windows caches the MSI installer files (I believe they are cached in the `C:\Windows\Installer` directory). Off the top of my head, I wouldn't know how much of a space saving in the layer is possible, but you could measure it.

As for hosting both ASP.NET and ASP.NET Core together, it begs the question why aren't you using separate containers for each of your applications? I'd love to understand your use case.

I'm closing this issue for now, but we might re-consider publishing this image in the future if there's sufficient demand for it.

**Comment by jmajoor** [comment]
Our application for the customer’s point of view is a website that we deliver as a container image. If they want to scale our app, they simply scale this container.

The website itself consists out of several web applications. As for the question “why don’t you make them all separate containers”. That sounds nice (and we thought about it), but creating micro services into separate containers has no benefit to our application. There is no benefit in our application from separate scaling of micro services. When things go into separate containers then you have to deal with compose files / services, dependencies between containers etc. You also need to deal with the fact that a container may be in a running state, but that doesn’t mean the services are in a running state. This means additional protections to make sure these services are stable, network / container discovery as well as configuration options to get it all started.
So there is considerable overhead to produce a multi container website and in our application it would have zero benefits. Right now a customer can launch a container and is up-and-running

Recently we migrated one of the web applications to ASP.NET Core and over time we will migrate the others as well. In this final end state we would still like to use IIS and the hosting bundle instead of going with nginx or some other proxy to handle the multiple ASP.NET Core applications in a single container.

Though it is possible to install ASP.NET Core in much the same way the ASP.NET Core image is doing this, there is no information on the hosting bundle part. There is no information what is installed and where it needs to be installed and there is also no zip file for the hosting bundle either. This is the reason why I am asking Microsoft to provide such an image. This could also be an IIS with ASP.NET Core hosting image without the ASP.NET part.

I did create an image (https://hub.docker.com/r/jmajoor/iis-aspnetcore/), but since this is all Microsoft components it would be nice if Microsoft would deliver this as a base image (as mentioned above maybe just the IIS with ASP.NET Core hosting).

- Johan
